version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: db_back
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${{secrets.DB_PASSWORD}}
      MYSQL_DATABASE: ${{secrets.DB_NAME}}
      MYSQL_USER: ${{secrets.DB_USER}}
      MYSQL_PASSWORD: ${{secrets.DB_PASSWORD}}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build: .
    container_name: dev2_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}
    depends_on:
      - db
volumes:
  db_data: